apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-frontend
  namespace: node
data:
  appConfig.js: |
    var appConfig = {
     API_URL: 'http://node.twnsnd.online:31033/api'
    };

---
apiVersion: v1
kind: Secret
metadata:
  name: front-dockerkey
  namespace: node
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJCSJhdXRoIjogImRIZHVjMjVrYm05a1pXcHpPa0pzYVdGMGMzUjNiMmxTWVhwM2NtRjBPU0U9IgoJCX0KCX0KfQ== #paste here your auth base64 token
type: kubernetes.io/dockerconfigjson

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: node
  labels:
    app: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: twnsndnodejs/frontend:latest
          resources:
            requests:
              memory: '128Mi'
              cpu: '100m'
            limits:
              memory: '512Mi'
              cpu: '300m'
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: '/static/appConfig.js'
              subPath: 'appConfig.js'
              name: config-files
      volumes:
        - configMap:
            defaultMode: 420
            name: cm-frontend
            optional: true
          name: config-files
      imagePullSecrets:
        - name: front-dockerkey

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  namespace: node
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 32043
