export enum ROUTE {
  HOME = '/',
  PROFILE = '/profile',
  PLATFORMS = '/platforms',
  SOLUTIONS = '/solutions',
  FILTERS = '/filters',
  PLATFORMS_DETAILS = '/platforms/:platformId',
  SIGN_UP = '/sign-up',
  SIGN_IN = '/sign-in',
  RESET_PASSWORD = '/reset-password',
  NEW_PASSWORD = '/new-password',
  PROFILE_SETTINGS = 'settings',
  PROFILE_FAVORITES = 'favorites',
  PROFILE_FAQ = 'faq',
  PROFILE_FAVORITES_PLATFORMS = 'platforms',
  PROFILE_FAVORITES_SOLUTIONS = 'solutions',
  PROFILE_HISTORY = 'history',
  ADMIN = '/admin/dashboard',
  ADMIN_BASE = '/admin',
  PROFILE_HISTORY_PLATFORMS = 'platforms',
  PROFILE_HISTORY_SOLUTIONS = 'solutions',
}
